require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.nvim-tree"
require "user.nvim-treesitter"
require "user.telescope"
require "user.autopairs"
require "user.gitsigns"
require "user.lualine"
require "user.bufferline"

vim.cmd "colorscheme tokyonight"

